backend/src/main/java/com/devmatch/backend/domain/user/entity/User.java

[BE] feat: User Entity 생성

---

backend/src/main/resources/application.properties
backend/src/main/resources/application.yml

[BE] feat: application.yml 설정

---

backend/src/main/java/com/devmatch/backend/domain/analysis/entity/AnalysisResult.java

AnalysisResult 엔티티 작업완료

---

backend/src/main/java/com/devmatch/backend/domain/analysis/repository/AnalysisRepository.java

[BE] feat: AnalysisRepository 구현

---

backend/src/main/java/com/devmatch/backend/domain/application/entity/Application.java
backend/src/main/java/com/devmatch/backend/domain/application/entity/SkillScore.java
backend/src/main/java/com/devmatch/backend/domain/application/enums/ApplicationStatus.java

Application, SkillScore 엔티티 구현

[BE] feat: Application, SkillScore 엔티티 구현

---

backend/.gitignore
backend/src/main/java/com/devmatch/backend/domain/user/controller/UserController.java
backend/src/main/java/com/devmatch/backend/domain/user/entity/User.java
backend/src/main/java/com/devmatch/backend/domain/user/repository/UserRepository.java
backend/src/main/java/com/devmatch/backend/domain/user/service/UserService.java

Close #17 
User 엔티티 주석처리한 코드는 무시하셔도 됩니다.

[BE] feat : User 도메인 관련 기능 작성

---

backend/src/main/java/com/devmatch/backend/domain/user/entity/User.java
backend/src/main/java/com/devmatch/backend/domain/user/service/UserService.java

[BE] chore : UserService Ex 수정

---

backend/src/main/java/com/devmatch/backend/domain/application/controller/ApplicationController.java
backend/src/main/java/com/devmatch/backend/domain/application/dto/ApplicationDetailResponse.java
backend/src/main/java/com/devmatch/backend/domain/application/dto/ApplicationDto.java
backend/src/main/java/com/devmatch/backend/domain/application/dto/ApplicationStatusUpdateRequest.java
backend/src/main/java/com/devmatch/backend/domain/application/dto/request/ApplicationStatusUpdateRequest.java
backend/src/main/java/com/devmatch/backend/domain/application/dto/response/ApplicationDetailResponseDto.java
backend/src/main/java/com/devmatch/backend/domain/application/repository/ApplicationRepository.java
backend/src/main/java/com/devmatch/backend/domain/application/repository/SkillScoreRepository.java
backend/src/main/java/com/devmatch/backend/domain/application/service/ApplicationService.java

ApplicationController 과 ApplicationService 의 지원서 상세 정보를 조회하는 기능 구현.

[BE] feat: 지원서 상세 정보 조회 구현

---

backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectDetailResponse.java
backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
backend/src/main/java/com/devmatch/backend/domain/project/entity/ProjectStatus.java
backend/src/main/java/com/devmatch/backend/domain/project/mapper/ProjectMapper.java
backend/src/main/java/com/devmatch/backend/domain/project/repository/ProjectRepository.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
backend/src/main/java/com/devmatch/backend/exception/GlobalExceptionHandler.java

[BE] Project 생성 API 추가

---

backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java

[BE] refactor: 기간 컬럼 추가에 따른 코드 수정

---

backend/src/main/java/com/devmatch/backend/domain/auth/controller/AuthController.java
backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
backend/src/main/java/com/devmatch/backend/domain/user/controller/UserController.java
backend/src/main/java/com/devmatch/backend/domain/user/entity/User.java

Close #43 
일단 다른 분들 삭제 api 작업하실 때 쓰라고 먼저 push 하겠습니다.
이제 OAuth 작업하겠습니다

[BE] feat : User add method

---

backend/src/main/java/com/devmatch/backend/domain/application/controller/ApplicationController.java
backend/src/main/java/com/devmatch/backend/domain/application/service/ApplicationService.java

프론트에서 테스트 하기 위한 지원서 상태 변경 API 임시로 작성

[BE] feat: 지원서 상태 변경 API 임시 코드 작성

---

backend/src/main/java/com/devmatch/backend/domain/application/entity/Application.java

지원서 승인 상태를 기본값을 PENDING으로 부여
private ApplicationStatus status; -> private ApplicationStatus status = ApplicationStatus.PENDING;

[BE] fix: 지원서 승인 상태를 기본값을 PENDING으로 부여

---

backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
backend/src/main/java/com/devmatch/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/com/devmatch/backend/exception/SameStatusException.java

[BE] 프로젝트 상태 수정 API 추가

---

frontend/src/app/projects/create/page.tsx
frontend/src/lib/api/project.ts

[FE] fix: 기술스택 전송 형식 수정 - String으로 백엔드 전송, List<String>으로 응답 받기

---

backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java

[BE] feat: 역할 배분 내용 수정 API 구현

---

backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java

[BE] feat: 프로젝트 삭제 API 구현

---

backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java

[BE] feat: 프로젝트 지원서 작성 API 구현

---

frontend/src/app/API_USAGE.md

[FE] docs:api 사용 문서화

---

backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectApplyRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectContentUpdateRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectStatusUpdateRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/entity/Project.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
backend/src/main/java/com/devmatch/backend/exception/SameStatusException.java

[BE] 프로젝트 삭제에 대한 연간관계 추가 및 유효성 검사 강화

---

frontend/src/app/projects/[id]/page.tsx
frontend/src/lib/api/analysis.ts
frontend/src/lib/api/application.ts
frontend/src/lib/api/index.ts
frontend/src/lib/api/project.ts
frontend/src/lib/api/user.ts
frontend/src/types/index.ts

[FE] refactor: lib/* api/* 각 페이지별 코드 변경

---

backend/src/main/resources/application.yml

yml 에서 env 파일인식하는 부분이 영상에서
import: optional:file:.env[.properties] 였는데 이대로 하니깐 파일 인식이 안되네요? 왜 안됐던건진 몰?루입니다
뒤에 .default 붙이니까 되네요

[BE] chore : yml 수정

---

backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
backend/src/main/resources/application-dev.yml

[BE] 개발용 DBMS 수정 및 미흡한 조건 검사 수정

---

backend/src/main/java/com/devmatch/backend/domain/project/controller/ProjectController.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectApplyRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectCreateRequest.java
backend/src/main/java/com/devmatch/backend/domain/project/dto/ProjectDetailResponse.java
backend/src/main/java/com/devmatch/backend/domain/project/mapper/ProjectMapper.java
backend/src/main/java/com/devmatch/backend/domain/project/service/ProjectService.java
backend/src/main/java/com/devmatch/backend/global/rq/Rq.java

[BE] 사용자를 인증 객체를 활용하는 방식으로 수정

---

backend/src/main/java/com/devmatch/backend/domain/home/controller/HomeController.java
backend/src/main/java/com/devmatch/backend/domain/user/controller/UserController.java
backend/src/main/java/com/devmatch/backend/domain/user/service/UserService.java
backend/src/main/java/com/devmatch/backend/global/security/CustomAuthenticationFilter.java
backend/src/main/java/com/devmatch/backend/global/security/CustomOAuth2LoginSuccessHandler.java

[BE] chore : 수정

---

backend/src/main/java/com/devmatch/backend/domain/home/controller/HomeController.java
backend/src/main/java/com/devmatch/backend/domain/user/service/AuthTokenService.java
backend/src/main/java/com/devmatch/backend/global/security/CustomAuthenticationFilter.java
backend/src/main/java/com/devmatch/backend/global/security/SecurityConfig.java

[BE] feat : 필터 URL 추가

---

backend/src/main/java/com/devmatch/backend/domain/user/entity/User.java
backend/src/main/java/com/devmatch/backend/global/rq/Rq.java
backend/src/main/java/com/devmatch/backend/global/security/CustomAuthenticationFilter.java
backend/src/main/java/com/devmatch/backend/global/security/CustomOAuth2LoginSuccessHandler.java
backend/src/test/java/com/devmatch/backend/BackendApplicationTests.java

[BE] feat : User 클래스에 이미지 가져오는기능 추가

---

README.md
frontend/src/lib/api/index.ts

[FE] refactor: README.md 개편

---

frontend/src/components/ui/ApplicationAnalysisModal.tsx

Fix apiUrl scope issue in ApplicationAnalysisModal
- Move apiUrl declaration to outer scope
- Resolves Vercel build error

[FE] fix: Vercel build error - apiUrl scope

---

frontend/src/app/projects/[id]/page.tsx

APPROVED 상태에서 지원취소 버튼 숨김
- PENDING 상태에서만 지원취소 가능
- 승인된 지원자는 지원취소 불가

[FE] fix: 승인된 지원자 지원취소 제한

---

frontend/src/app/projects/[id]/page.tsx

- 승인된 지원자도 지원취소 가능하도록 UI 수정
- 지원취소 시 프로젝트 currentTeamSize 자동 업데이트
- 승인된 지원자 지원취소 시 팀크기 감소 확인

승인된 지원자 지원취소 허용

---

frontend/src/app/projects/[id]/page.tsx
frontend/src/components/ui/ApplicationDetailsModal.tsx

프로젝트 생성자가 지원자 승인/거절 시 지원서 상세정보를 볼 수 있는 버튼 추가

[FE] feat: 프로젝트 생성자 지원서 보기 기능 추가
